version: '3.7'
services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/timezonesearch
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_CONNECTION_LIMIT=100
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=timezones
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timezones
    expose:
      - "3306"
      - "3308"
    ports:
      - "3308:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080